import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'

import './globals.css'

export const metadata: Metadata = {
  title: 'Sebinash',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        {children}
        <Toaster
          position='top-center'
          reverseOrder={false}
          toastOptions={{
            duration: 5000,
          }}
        />
      </body>
    </html>
  )
}
